### ISSUE TITLE
Question: Does ImagePipeline.Shared.RemoveImageFromCacheFor(url) work?

### ISSUE THREAD

**Issue by IainS1986** [roubachof/NukeProxy#21]
I'm having some issues with using `ImagePipeline.Shared.RemoveImageFromCacheFor(url)`

I have Nuke Proxy working fine in a .net-ios project on .net8.0 - images are all loading fine using NSUrls (I'm using file path based ones so they are all file:// style urls, no remote web urls).

Sometimes, an image can change based on the users interactions and so I want to clear the cache just for that one image, the above function seems the right one, but it never seems to clear it. All subsequent calls to load the image for the url still load the previous (old) image.

I can call `ImagePipeline.Shared.RemoveAllCaches();` to do a hard clear on the whole cache, and that does work - but obviously its quite destructive.

I'm wondering if my usage of `RemoveImageFromCacheFor` is wrong or its an issue with `file://` based urls?

**Comment by Cheesebaron** [comment]
Hopefully it is fixed in #22

**Comment by IainS1986** [comment]
Hi @Cheesebaron  - is this fix expected to be in 3.0.1?

I've updated to that but `ImagePipeline.Shared.RemoveImageFromCacheFor(url)` still doesn't appear to be clearing the cache for the path I pass in.

I'm using local file paths, so `file://var/mobile/Containers/Data/Application/xxx/Documents/SomeImageFile.png` for example..... (created from a `NSUrl.FromFileName` call)

**Comment by Cheesebaron** [comment]
It should be. However, does it make sense to cache local images when they are on disk already?

**Comment by IainS1986** [comment]
So our use case is having thumbnail images for files that have been created within the app - and we have a files/folders style view.

So the thumbnails are stored locally yes, but we have a nice scrolling table view with cells showing the images and with (I assumed tbh) in memory caching of those thumbnails.

So performance of the scrolling list is really the main use case for this, although I admit I haven't actually tested for a very long time just loading the thumbnails from disk each time.

The issue though, is if the user makes a change to a file and resaves it, this regenerates the thumbnail but Nuke Proxy doesn't appear to invalidate the cache for the given key - we're having to invalidate the whole cache to get the new thumbnail to load in.

**Comment by Cheesebaron** [comment]
Reopened this. Will have a look to see what can be done to fix this or find a workaround.
